# .goreleaser.yml
project_name: dumpr

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Branch={{.Branch}} -X main.LatestCommit={{.FullCommit}} -X main.CommitDate={{ .CommitDate }} -X main.BuiltBy=goreleaser  -X "main.GitRepo={{.GitURL}}" -X "main.BuildDate={{.Date}}"

archives:
  # Archive name template.
  # Defaults:
  # - if format is `tar.gz`, `tar.xz`, `gz` or `zip`:
  #   - `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}`
  # - if format is `binary`:
  #   - `{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}`
  # - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true

    # ID of this archive.
    # Defaults to `default`.
    id: dumpr

    files:
      - LICENSE
      - README.md
      - 'web/*'

    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request


dockers:
  - image_templates: ["ghcr.io/alexj212/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/alexj212/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/alexj212/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    extra_files:
      - LICENSE
      - README.md
      - web

docker_manifests:

  - name_template: ghcr.io/alexj212/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/alexj212/{{ .ProjectName }}:{{ .Version }}-amd64

  - name_template: ghcr.io/alexj212/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/alexj212/{{ .ProjectName }}:{{ .Version }}-amd64
