version: '3'

networks:
  web:
    external: true

services:
  dumpr:
    image: ghcr.io/alexj212/dumpr:latest
    container_name: dumpr
    command: /app/dumpr --webDir=/app/web --publicUrl=https://dumpr.io --publicBinEndpoint=dumpr.io:48081
    ports:
      - "48080:8080"
      - "48081:8081"
    labels:
      - traefik.enable=true
      - traefik.http.routers.dumpr-https.rule=Host(`dumpr.io`)
      - traefik.http.routers.dumpr-https.entrypoints=https
      - traefik.http.routers.dumpr-https.tls=true
      - traefik.http.routers.dumpr-https.tls.certresolver=cloudflare
      - traefik.http.routers.dumpr-https.tls.domains[0].main=florida.dumpr.io
      - traefik.http.routers.dumpr-https.tls.domains[0].sans=*.florida.dumpr.io
      ##
      - traefik.http.routers.dumpr.service=dumpr-svc
      ## HTTP Services
      - traefik.http.services.dumpr-svc.loadbalancer.server.port=8080
      - traefik.http.services.dumpr-svc.loadbalancer.server.scheme=http
      - traefik.http.services.dumpr-svc.loadbalancer.passhostheader=true

    networks:
      - web





