# syntax=docker/dockerfile:1
FROM golang:1.20

WORKDIR /build
COPY ./ /build

RUN ls -latr /build
RUN go mod download
RUN make dumpr

RUN mkdir /app

RUN bash -c 'mkdir -p {/app,/conf};cp /build/bin/dumpr /app'

EXPOSE 8080
EXPOSE 8081

CMD [ "/app/dumpr" ]
